import React from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Github } from 'lucide-react';

const Projects = () => {
  const projects = [
    {
      title: "This Website",
      description: "A modern portfolio website built with AI assistance using cutting-edge web technologies for fast performance and beautiful design.",
      technologies: ["React", "TypeScript", "Vite", "Tailwind", "shadcn"],
      github: "https://github.com/TomStacy/Resume-Tom-Stacy"
    },
    {
      title: "LLM Evaluation",
      description: "Compare and evaluate large language models (LLMs) against one another using questions generated by the LLMs.",
      technologies: ["Python", "Jupyter Notebooks", "UV", "Ruff"],
      github: "https://github.com/TomStacy/llm-evaluator"
    },
    {
      title: "Coming Soon",
      description: "Financial data analysis tool leveraging machine learning to provide insights and predictions for investment strategies.",
      technologies: ["Python"]
    }
  ];

  return (
    <section id="projects" className="section bg-background">
      <div className="container-tight">
        <div className="space-y-4 mb-16 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-primary">
            Hobby Projects
          </h2>
          <div className="w-20 h-1 bg-primary mx-auto"></div>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            A selection of projects I've developed. These represent my hands-on technical expertise and passion for innovation.
          </p>
        </div>

        <div className="grid md:grid-cols-3 gap-8">
          {projects.map((project, index) => (
            <Card key={index} className="overflow-hidden border-2 transition-all duration-300 border-border hover:border-primary/50 bg-gradient-to-b from-muted/30 to-background backdrop-blur-sm">
              <CardContent className="p-6">
                <h3 className="text-xl font-bold mb-3 text-primary">
                  {project.title}
                </h3>
                <p className="text-muted-foreground mb-4">
                  {project.description}
                </p>
                
                <div className="mb-6">
                  <div className="flex flex-wrap gap-2">
                    {project.technologies.map((tech, i) => (
                      <span key={i} className="bg-muted text-muted-foreground text-xs py-1 rounded">
                        {tech}
                      </span>
                    ))}
                  </div>
                </div>
                
                {project.github && (
                  <Button 
                    variant="outline" 
                    size="sm" 
                    className="w-full flex items-center justify-center gap-2 transition-all hover:bg-primary hover:text-primary-foreground hover:border-primary hover:shadow-md hover:scale-105"
                    asChild
                  >
                    <a href={project.github} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2">
                      <Github className="h-4 w-4" />
                      View on GitHub
                    </a>
                  </Button>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
        
        <div className="mt-12 text-center">
          <Button 
            className="bg-primary hover:bg-primary/90 text-primary-foreground transition-all hover:shadow-md"
            size="lg"
            asChild
          >
            <a href="https://github.com/TomStacy" target="_blank" rel="noopener noreferrer" className="flex items-center">
              <Github className="mr-2 h-4 w-4" />
              View All GitHub Projects
            </a>
          </Button>
        </div>
      </div>
    </section>
  );
};

export default Projects;
